import type { HouseholdApp } from '../apps';

/**
 * An app's family logo. The markup is trusted: generated by the kit's logoSvg from a fixed glyph.
 * `hh-logo` gives the tile its lighter colour and faint edge in dark (kit theme.css).
 */
export function AppIcon({ app, size }: { app: HouseholdApp; size: number }) {
  return (
    <span
      aria-hidden="true"
      className="hh-logo inline-flex shrink-0 [&>svg]:h-full [&>svg]:w-full"
      style={{ width: size, height: size }}
      dangerouslySetInnerHTML={{ __html: app.icon }}
    />
  );
}
